version: '3'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - proxy

  odoo-dnd-generale-17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10017:8069"
      - "20017:8072" # live chat
    tty: true
    command: --
    #entrypoint: /entrypoint.sh
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17@2023
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      #- ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo-dnd-generale-17.entrypoints=http"
      # NOW YOU NEED TO SETUP A DOMAIN OR SUB DOAMIN DNS WITH YOUR IP AND WRITE IT BELOW : 
      - "traefik.http.routers.odoo-dnd-generale-17.rule=Host(`dnd-generale.dndc.pro`)"
      - "traefik.http.middlewares.odoo-dnd-generale-17-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.odoo-dnd-generale-17.middlewares=odoo-dnd-generale-17-https-redirect"
      - "traefik.http.routers.odoo-dnd-generale-17-secure.entrypoints=https"
      # NOW YOU NEED TO SETUP A DOMAIN OR SUB DOAMIN DNS WITH YOUR IP AND WRITE IT BELOW : 
      - "traefik.http.routers.odoo-dnd-generale-17-secure.rule=Host(`dnd-generale.dndc.pro`)"
      - "traefik.http.routers.odoo-dnd-generale-17-secure.tls=true"
      - "traefik.http.routers.odoo-dnd-generale-17-secure.service=odoo-dnd-generale-17"
      - "traefik.http.services.odoo-dnd-generale-17.loadbalancer.server.port=8069"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
